//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCargos
    {
        public int car_Id { get; set; }
        public string car_Descripcion { get; set; }
        public Nullable<bool> car_Estado { get; set; }
        public int car_Usuariocrea { get; set; }
        public System.DateTime car_Fechacrea { get; set; }
        public Nullable<int> car_Usuariomodifica { get; set; }
        public Nullable<System.DateTime> car_Fechamodifica { get; set; }
    }
}
