//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCatalogoDeIngresos
    {
        public tbCatalogoDeIngresos()
        {
            this.tbTipoPlanillaDetalleIngreso = new HashSet<tbTipoPlanillaDetalleIngreso>();
            this.tbEmpleadoBonos = new HashSet<tbEmpleadoBonos>();
            this.tbEmpleadoComisiones = new HashSet<tbEmpleadoComisiones>();
        }
    
        public int cin_IdIngreso { get; set; }
        public string cin_DescripcionIngreso { get; set; }
        public Nullable<int> cin_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> cin_FechaCrea { get; set; }
        public Nullable<int> cin_UsuarioModifica { get; set; }
        public Nullable<int> cin_FechaModifica { get; set; }
    
        public virtual ICollection<tbTipoPlanillaDetalleIngreso> tbTipoPlanillaDetalleIngreso { get; set; }
        public virtual ICollection<tbEmpleadoBonos> tbEmpleadoBonos { get; set; }
        public virtual ICollection<tbEmpleadoComisiones> tbEmpleadoComisiones { get; set; }
    }
}
