//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCompetenciasPersona
    {
        public int cope_Id { get; set; }
        public int per_Id { get; set; }
        public int comp_Id { get; set; }
        public int cope_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> cope_FechaCrea { get; set; }
        public Nullable<int> cope_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> cope_FechaModifica { get; set; }
    }
}
