//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCompetenciasRequisicion
    {
        public int creq_Id { get; set; }
        public int req_Id { get; set; }
        public int comp_Id { get; set; }
        public int creq_UsuarioCrea { get; set; }
        public System.DateTime creq_FechaCrea { get; set; }
        public Nullable<int> creq_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> req_FechaModifica { get; set; }
    }
}
