//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDeduccionesExtraordinarias
    {
        public int dex_IdDeduccionesExtra { get; set; }
        public Nullable<int> eqco_Id { get; set; }
        public Nullable<decimal> dex_MontoInicial { get; set; }
        public Nullable<decimal> dex_MontoRestante { get; set; }
        public string dex_ObservacionesComentarios { get; set; }
        public Nullable<int> cde_IdDeducciones { get; set; }
        public Nullable<decimal> dex_Cuota { get; set; }
        public Nullable<int> dex_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> dex_FechaCrea { get; set; }
        public Nullable<int> dex_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> dex_FechaModifica { get; set; }
    
        public virtual tbCatalogoDeDeducciones tbCatalogoDeDeducciones { get; set; }
        public virtual tbEquipoEmpleados tbEquipoEmpleados { get; set; }
    }
}
