//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDepartamentos
    {
        public int depto_Id { get; set; }
        public int suc_Id { get; set; }
        public int car_Id { get; set; }
        public string depto_Descripcion { get; set; }
        public int depto_UsuarioCrea { get; set; }
        public System.DateTime depto_Fechacrea { get; set; }
        public Nullable<int> depto_Usuariomodifica { get; set; }
        public Nullable<System.DateTime> depto_Fechamodifica { get; set; }
    }
}
