//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmpleados
    {
        public tbEmpleados()
        {
            this.tbDeduccionInstitucionFinanciera = new HashSet<tbDeduccionInstitucionFinanciera>();
            this.tbEmpleadoBonos = new HashSet<tbEmpleadoBonos>();
            this.tbEmpleadoComisiones = new HashSet<tbEmpleadoComisiones>();
            this.tbHistorialDePago = new HashSet<tbHistorialDePago>();
            this.tbSueldos = new HashSet<tbSueldos>();
        }
    
        public int emp_Id { get; set; }
        public int per_Id { get; set; }
        public int car_Id { get; set; }
        public int area_Id { get; set; }
        public int jor_id { get; set; }
        public Nullable<bool> emp_Reingreso { get; set; }
        public Nullable<System.DateTime> emp_Fechaingreso { get; set; }
        public Nullable<bool> emp_Estado { get; set; }
        public string emp_Razoninactivacion { get; set; }
        public string emp_Razonsalida { get; set; }
        public Nullable<int> emp_CargoAnterior { get; set; }
        public Nullable<System.DateTime> emp_Fechadesalida { get; set; }
        public int emp_Usuariocrea { get; set; }
        public System.DateTime emp_Fechacrea { get; set; }
        public Nullable<int> emp_Usuariomodifica { get; set; }
        public Nullable<System.DateTime> emp_Fechamodifica { get; set; }
        public int cpla_IdPlanilla { get; set; }
    
        public virtual tbCatalogoDePlanillas tbCatalogoDePlanillas { get; set; }
        public virtual ICollection<tbDeduccionInstitucionFinanciera> tbDeduccionInstitucionFinanciera { get; set; }
        public virtual ICollection<tbEmpleadoBonos> tbEmpleadoBonos { get; set; }
        public virtual ICollection<tbEmpleadoComisiones> tbEmpleadoComisiones { get; set; }
        public virtual ICollection<tbHistorialDePago> tbHistorialDePago { get; set; }
        public virtual ICollection<tbSueldos> tbSueldos { get; set; }
    }
}
