//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmpleadoComisiones
    {
        public int cc_Id { get; set; }
        public int emp_Id { get; set; }
        public int cin_IdIngreso { get; set; }
        public Nullable<decimal> cc_Monto { get; set; }
        public Nullable<System.DateTime> cc_FechaRegistro { get; set; }
        public Nullable<bool> cc_Pagado { get; set; }
        public Nullable<int> cc_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> cc_FechaCrea { get; set; }
        public Nullable<int> cc_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> cc_FechaModifica { get; set; }
    
        public virtual tbCatalogoDeIngresos tbCatalogoDeIngresos { get; set; }
        public virtual tbEmpleados tbEmpleados { get; set; }
    }
}
