//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmpleadosAreas
    {
        public int coar_Id { get; set; }
        public int emp_Id { get; set; }
        public int are_Id { get; set; }
        public int coar_UsuarioCrea { get; set; }
        public System.DateTime coar_FechaCrea { get; set; }
        public Nullable<int> coar_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> coar_FechaModifica { get; set; }
    }
}
