//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEquipoTrabajo
    {
        public int eqtra_Id { get; set; }
        public Nullable<int> eqtra_codigo { get; set; }
        public string eqtra_Descripcion { get; set; }
        public string eqtra_observacion { get; set; }
        public Nullable<bool> eqtra_util { get; set; }
        public int eqtra_UsuarioCrea { get; set; }
        public System.DateTime eqtra_FechaCrea { get; set; }
        public Nullable<int> eqtra_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> eqtra_FechaModifica { get; set; }
    }
}
