//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEquipoEmpleados
    {
        public tbEquipoEmpleados()
        {
            this.tbDeduccionesExtraordinarias = new HashSet<tbDeduccionesExtraordinarias>();
        }
    
        public int eqco_Id { get; set; }
        public Nullable<int> emp_Id { get; set; }
        public Nullable<int> eqtra_Id { get; set; }
        public Nullable<System.DateTime> eqco_Fecha { get; set; }
        public int eqco_UsuarioCrea { get; set; }
        public System.DateTime eqco_FechaCrea { get; set; }
        public Nullable<int> eqco_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> eqco_FechaModifica { get; set; }
    
        public virtual ICollection<tbDeduccionesExtraordinarias> tbDeduccionesExtraordinarias { get; set; }
    }
}
