//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFaseSeleccion
    {
        public int fsel_Id { get; set; }
        public int fare_Id { get; set; }
        public System.DateTime fare_fecha { get; set; }
        public int fsel_UsuarioCrea { get; set; }
        public System.DateTime fsel_FechaCrea { get; set; }
        public Nullable<int> fsel_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> fsel_FechaModifica { get; set; }
    }
}
