//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHabilidades
    {
        public int habi_Id { get; set; }
        public string habi_Descripcion { get; set; }
        public int habi_UsuarioCrea { get; set; }
        public System.DateTime habi_FechaCrea { get; set; }
        public Nullable<int> habi_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> habi_FechaModifica { get; set; }
    }
}
