//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHabilidadesRequisicion
    {
        public int hreq_Id { get; set; }
        public int req_Id { get; set; }
        public int habi_Id { get; set; }
        public int hreq_UsuarioCrea { get; set; }
        public System.DateTime hreq_FechaCrea { get; set; }
        public Nullable<int> hreq_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> hreq_FechaModifica { get; set; }
    }
}
