//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHabilidadesPersona
    {
        public int hape_Id { get; set; }
        public Nullable<int> per_Id { get; set; }
        public Nullable<int> habi_Id { get; set; }
        public int hape_UsuarioCrea { get; set; }
        public System.DateTime hape_FechaCrea { get; set; }
        public Nullable<int> hape_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> hape_FechaModifica { get; set; }
    }
}
