//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHistorialAmonestaciones
    {
        public int hamo_Id { get; set; }
        public Nullable<int> emp_Id { get; set; }
        public Nullable<int> tamo_Id { get; set; }
        public int hamo_Anterior { get; set; }
        public string hamo_Observacion { get; set; }
        public int hamo_UsuarioCrea { get; set; }
        public System.DateTime hamo_FechaCrea { get; set; }
        public Nullable<int> hamo_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> hamo_FechaModifica { get; set; }
    }
}
