//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHistorialContrataciones
    {
        public int hcon_Id { get; set; }
        public int per_Id { get; set; }
        public int area_Id { get; set; }
        public System.DateTime hcon_FechaContratado { get; set; }
        public int hcon_UsuarioCrea { get; set; }
        public System.DateTime hcon_FechaCrea { get; set; }
        public Nullable<int> hcon_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> hcon_FechaModifica { get; set; }
    }
}
