//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHistorialLiquidaciones
    {
        public int hliq_Id { get; set; }
        public int emp_Id { get; set; }
        public string hliq_Observaciones { get; set; }
        public int hliq_UsuarioCrea { get; set; }
        public System.DateTime hliq_FechaCrea { get; set; }
        public Nullable<int> hliq_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> hliq_FechaModifica { get; set; }
    }
}
