//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHistorialDePago
    {
        public tbHistorialDePago()
        {
            this.tbHistorialDeduccionPago = new HashSet<tbHistorialDeduccionPago>();
            this.tbHistorialDeIngresosPago = new HashSet<tbHistorialDeIngresosPago>();
        }
    
        public int hipa_IdHistorialDePago { get; set; }
        public int emp_Id { get; set; }
        public Nullable<decimal> hipa_SueldoNeto { get; set; }
        public Nullable<System.DateTime> hipa_FechaInicio { get; set; }
        public Nullable<System.DateTime> hipa_FechaFin { get; set; }
        public Nullable<System.DateTime> hipa_FechaPago { get; set; }
        public Nullable<int> hipa_Año { get; set; }
        public Nullable<int> hipa_Mes { get; set; }
        public Nullable<int> peri_IdPeriodo { get; set; }
        public Nullable<int> hipa_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> hipa_FechaCrea { get; set; }
        public Nullable<int> hipa_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> hipa_FechaModifica { get; set; }
    
        public virtual ICollection<tbHistorialDeduccionPago> tbHistorialDeduccionPago { get; set; }
        public virtual ICollection<tbHistorialDeIngresosPago> tbHistorialDeIngresosPago { get; set; }
        public virtual tbEmpleados tbEmpleados { get; set; }
        public virtual tbPeriodos tbPeriodos { get; set; }
    }
}
