//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHistorialincapacidades
    {
        public int hinc_Id { get; set; }
        public int Emp_Id { get; set; }
        public int ticn_Id { get; set; }
        public int hinc_PorcentajeIndemnizado { get; set; }
        public string hinc_Observacion { get; set; }
        public Nullable<System.DateTime> hinc_Fechainicio { get; set; }
        public Nullable<System.DateTime> hinc_Fechafin { get; set; }
        public int hinc_Usuariocrea { get; set; }
        public System.DateTime hinc_Fechacrea { get; set; }
        public Nullable<int> hinc_Usuariomodifica { get; set; }
        public Nullable<System.DateTime> hinc_Fechamodifica { get; set; }
    }
}
