//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHistorialCargos
    {
        public int hcar_Id { get; set; }
        public Nullable<int> emp_Id { get; set; }
        public Nullable<int> car_Id { get; set; }
        public Nullable<System.DateTime> hcar_Fecha { get; set; }
        public Nullable<int> hcar_Usuariocrea { get; set; }
        public Nullable<System.DateTime> hcar_Fechacrea { get; set; }
        public Nullable<int> hcar_Usuariomodifica { get; set; }
        public Nullable<System.DateTime> hcar_Fechamodifica { get; set; }
    }
}
