//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbidiomas
    {
        public int idi_Id { get; set; }
        public string idi_Descripcion { get; set; }
        public int idi_UsuarioCrea { get; set; }
        public System.DateTime idi_FechaCrea { get; set; }
        public Nullable<int> idi_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> idi_FechaModifica { get; set; }
    }
}
