//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbIdiomaPersona
    {
        public int idpe_Id { get; set; }
        public Nullable<int> per_Id { get; set; }
        public Nullable<int> idi_Id { get; set; }
        public int idpe_UsuarioCrea { get; set; }
        public System.DateTime idpe_FechaCrea { get; set; }
        public Nullable<int> idpe_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> idpe_FechaModifica { get; set; }
    }
}
