//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbInstitucionesFinancieras
    {
        public tbInstitucionesFinancieras()
        {
            this.tbDeduccionInstitucionFinanciera = new HashSet<tbDeduccionInstitucionFinanciera>();
        }
    
        public int insf_IdInstitucionFinanciera { get; set; }
        public string insf_DescInstitucionFinanc { get; set; }
        public string insf_Contacto { get; set; }
        public string insf_Telefono { get; set; }
        public string insf_Correo { get; set; }
        public Nullable<int> insf_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> insf_FechaCrea { get; set; }
        public Nullable<int> insf_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> insf_FechaModifica { get; set; }
        public Nullable<int> emp_Id { get; set; }
    
        public virtual ICollection<tbDeduccionInstitucionFinanciera> tbDeduccionInstitucionFinanciera { get; set; }
    }
}
