//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbJornadas
    {
        public tbJornadas()
        {
            this.tbSalarioPorHora = new HashSet<tbSalarioPorHora>();
        }
    
        public int jor_Id { get; set; }
        public int hor_Id { get; set; }
        public string jor_Descripcion { get; set; }
        public int jor_UsuarioCrea { get; set; }
        public System.DateTime jor_FechaCrea { get; set; }
        public Nullable<int> jor_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> jor_FechaModifica { get; set; }
    
        public virtual ICollection<tbSalarioPorHora> tbSalarioPorHora { get; set; }
    }
}
