//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPrestaciones
    {
        public int pres_Id { get; set; }
        public bool pres_DerechoPreaviso { get; set; }
        public decimal pres_Preaviso { get; set; }
        public decimal pres_DecimoTercer { get; set; }
        public decimal pres_Catorceabo { get; set; }
        public int pres_UsuarioCrea { get; set; }
        public System.DateTime pres_FechaCrea { get; set; }
        public Nullable<int> pres_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> pres_FechaModifica { get; set; }
    }
}
