//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRazonDespidos
    {
        public int rdes_id { get; set; }
        public string rdes_descripcion { get; set; }
        public int rdes_usuariocrea { get; set; }
        public System.DateTime rdes_fechacrea { get; set; }
        public Nullable<int> rdes_usuariomodifica { get; set; }
        public Nullable<System.DateTime> rdes_fechamodifica { get; set; }
    }
}
