//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRazonRenuncias
    {
        public int rren_id { get; set; }
        public string rren_descripcion { get; set; }
        public int rren_usuariocrea { get; set; }
        public System.DateTime rren_fechacrea { get; set; }
        public Nullable<int> rren_usuariomodifica { get; set; }
        public Nullable<System.DateTime> rren_fechamodifica { get; set; }
    }
}
