//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRamaActividad
    {
        public tbRamaActividad()
        {
            this.tbSalarioPorHora = new HashSet<tbSalarioPorHora>();
        }
    
        public int rama_Id { get; set; }
        public string rama_Descripcion { get; set; }
        public Nullable<int> rama_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> rama_FechaCrea { get; set; }
        public Nullable<int> rama_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> rama_FechaModifica { get; set; }
    
        public virtual ICollection<tbSalarioPorHora> tbSalarioPorHora { get; set; }
    }
}
