//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRequisicionPersonal
    {
        public int rper_Id { get; set; }
        public int emp_Id { get; set; }
        public int area_Id { get; set; }
        public string rper_plaza { get; set; }
        public string rper_Descripcion { get; set; }
        public int rper_Usuariocrea { get; set; }
        public System.DateTime rper_Fechacrea { get; set; }
        public Nullable<int> rper_Usuariomodifica { get; set; }
        public Nullable<System.DateTime> rper_Fechamodifica { get; set; }
    }
}
