//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSalarioPorHora
    {
        public int saph_Idsaph { get; set; }
        public Nullable<int> rama_Id { get; set; }
        public Nullable<decimal> saph_SalarioMinimo { get; set; }
        public Nullable<int> jor_Id { get; set; }
        public Nullable<decimal> saph_Monto { get; set; }
        public Nullable<int> saph_TamanoEmpresaInicial { get; set; }
        public Nullable<int> saph_TamanoEmpresaFinal { get; set; }
        public Nullable<int> saph_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> saph_FechaCrea { get; set; }
        public Nullable<int> saph_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> saph_FechaModifica { get; set; }
    
        public virtual tbRamaActividad tbRamaActividad { get; set; }
        public virtual tbJornadas tbJornadas { get; set; }
    }
}
