//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSeleccionCandidatos
    {
        public int scan_Id { get; set; }
        public int per_Id { get; set; }
        public int fare_Id { get; set; }
        public Nullable<System.DateTime> scan_fecha { get; set; }
        public int rper_Id { get; set; }
        public int scan_Usuariocrea { get; set; }
        public System.DateTime scan_Fechacrea { get; set; }
        public Nullable<int> scan_Usuariomodifica { get; set; }
        public Nullable<System.DateTime> scan_Fechamodifica { get; set; }
    }
}
