//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSueldos
    {
        public int hsue_Id { get; set; }
        public int emp_Id { get; set; }
        public int tmon_Id { get; set; }
        public string hsue_Cantidad { get; set; }
        public Nullable<int> hsue_SueldoAnterior { get; set; }
        public int hsue_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> hsue_FechaCrea { get; set; }
        public Nullable<int> hsue_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> hsue_FechaModifica { get; set; }
    
        public virtual tbEmpleados tbEmpleados { get; set; }
    }
}
