//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTitulos
    {
        public int titu_Id { get; set; }
        public string titu_Titulos { get; set; }
        public int titu_UsuarioCrea { get; set; }
        public System.DateTime titu_Fechacrea { get; set; }
        public Nullable<int> titu_Usuariomodifica { get; set; }
        public Nullable<System.DateTime> titu_FechaModifica { get; set; }
    }
}
