//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTipoAmonestaciones
    {
        public int tamo_Id { get; set; }
        public string tamo_Descripcion { get; set; }
        public int tamo_UsuarioCrea { get; set; }
        public System.DateTime tamo_FechaCrea { get; set; }
        public Nullable<int> tamo_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> tamo_FechaModifica { get; set; }
    }
}
