//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTipoPlanillaDetalleIngreso
    {
        public tbTipoPlanillaDetalleIngreso()
        {
            this.tbHistorialDeIngresosPago = new HashSet<tbHistorialDeIngresosPago>();
        }
    
        public int tpdi_IdDetallePlanillaIngreso { get; set; }
        public Nullable<int> cin_IdIngreso { get; set; }
        public Nullable<int> cpla_IdPlanilla { get; set; }
        public Nullable<int> tpdi_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> tpdi_FechaCrea { get; set; }
        public Nullable<int> tpdi_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> tpdi_FechaModifica { get; set; }
    
        public virtual tbCatalogoDeIngresos tbCatalogoDeIngresos { get; set; }
        public virtual tbCatalogoDePlanillas tbCatalogoDePlanillas { get; set; }
        public virtual ICollection<tbHistorialDeIngresosPago> tbHistorialDeIngresosPago { get; set; }
    }
}
