//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTitulosPersona
    {
        public int tipe_Id { get; set; }
        public int per_Id { get; set; }
        public int titu_Id { get; set; }
        public int tipe_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> tipe_FechaCrea { get; set; }
        public Nullable<int> tipe_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> tipe_FechaModifica { get; set; }
    }
}
