//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTipoDeduccion
    {
        public tbTipoDeduccion()
        {
            this.tbCatalogoDeDeducciones = new HashSet<tbCatalogoDeDeducciones>();
        }
    
        public int tde_IdTipoDedu { get; set; }
        public string tde_Descripcion { get; set; }
        public Nullable<int> tde_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> tde_FechaCrea { get; set; }
        public Nullable<int> tde_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> tde_FechaModifica { get; set; }
    
        public virtual ICollection<tbCatalogoDeDeducciones> tbCatalogoDeDeducciones { get; set; }
    }
}
