//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTipoIncapacidades
    {
        public int ticn_Id { get; set; }
        public string ticn_Descripcion { get; set; }
        public int ticn_Usuariocrea { get; set; }
        public System.DateTime ticn_Fechacrea { get; set; }
        public Nullable<int> ticn_Usuariomodifica { get; set; }
        public Nullable<System.DateTime> ticn_Fechamodifica { get; set; }
    }
}
