//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTipoHoras
    {
        public int tiho_Id { get; set; }
        public string tiho_Descripcion { get; set; }
        public int tiho_recargo { get; set; }
        public Nullable<bool> tiho_Estado { get; set; }
        public int tiho_UsuarioCrea { get; set; }
        public System.DateTime tiho_FechaCrea { get; set; }
        public Nullable<int> tiho_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> tiho_FechaModifica { get; set; }
    }
}
