//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbVacaciones
    {
        public int vaca_Id { get; set; }
        public int emp_Id { get; set; }
        public Nullable<int> vaca_dias { get; set; }
        public int vaca_UsuarioCrea { get; set; }
        public System.DateTime vaca_FechaCrea { get; set; }
        public Nullable<int> vaca_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> vaca_FechaModifica { get; set; }
    }
}
